schema_version: "1.0"
pipelines:
  - id: clinical-annotation
    path: pipelines/clinical_annotation
    descriptor: pipelines/clinical_annotation/pipeline.yaml
    active: true
  - id: nextflow-data-smoke
    path: pipelines/sample-vcf-smoke
    descriptor: pipelines/sample-vcf-smoke/pipeline.yaml
    active: true
  - id: hail-cohort-gwas
    path: pipelines/hail_gwas
    descriptor: pipelines/hail_gwas/pipeline.yaml
    active: true
  - id: plink-case-control-gwas
    path: pipelines/plink_gwas
    descriptor: pipelines/plink_gwas/pipeline.yaml
    active: true
  - id: hail-cohort-prs
    path: pipelines/hail_prs
    descriptor: pipelines/hail_prs/pipeline.yaml
    active: true
